// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFlZecSdjv6aJ2pLtmCQJm3XnSfRo7KvE',
    appId: '1:1020777710069:web:d6b79302a9dd660bb7a0bc',
    messagingSenderId: '1020777710069',
    projectId: 'skill-stack-5e275',
    authDomain: 'skill-stack-5e275.firebaseapp.com',
    storageBucket: 'skill-stack-5e275.firebasestorage.app',
    measurementId: 'G-Y2TNRL19GV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBowF90RClbUcv6d6VC9hNDkxgwjnIn70',
    appId: '1:1020777710069:android:30915d4d5552a32cb7a0bc',
    messagingSenderId: '1020777710069',
    projectId: 'skill-stack-5e275',
    storageBucket: 'skill-stack-5e275.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2Gj9GC5qE0NXAQ2Df2SLiPwvi_Xk-U0g',
    appId: '1:1020777710069:ios:f169182d62cb0db8b7a0bc',
    messagingSenderId: '1020777710069',
    projectId: 'skill-stack-5e275',
    storageBucket: 'skill-stack-5e275.firebasestorage.app',
    iosClientId: '1020777710069-n1gjoa616gfr5ddag82ecuobtfloqhrf.apps.googleusercontent.com',
    iosBundleId: 'com.example.itMcq',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2Gj9GC5qE0NXAQ2Df2SLiPwvi_Xk-U0g',
    appId: '1:1020777710069:ios:f169182d62cb0db8b7a0bc',
    messagingSenderId: '1020777710069',
    projectId: 'skill-stack-5e275',
    storageBucket: 'skill-stack-5e275.firebasestorage.app',
    iosClientId: '1020777710069-n1gjoa616gfr5ddag82ecuobtfloqhrf.apps.googleusercontent.com',
    iosBundleId: 'com.example.itMcq',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFlZecSdjv6aJ2pLtmCQJm3XnSfRo7KvE',
    appId: '1:1020777710069:web:3c7e3e5df86a6675b7a0bc',
    messagingSenderId: '1020777710069',
    projectId: 'skill-stack-5e275',
    authDomain: 'skill-stack-5e275.firebaseapp.com',
    storageBucket: 'skill-stack-5e275.firebasestorage.app',
    measurementId: 'G-W0TQC0Z5ME',
  );
}
